@startuml
class User1 {}
class User2 {}
class Admin {}
class Nginx {
проксирует запросы
}
class Router {
Обрабатывает HTTP запросы от других частей проекта
void ConnectToBroker()
void SendMessage(subject string, payload any)
}
class LinkGenerator {
Генератор ссылок
void ConnectToBroker()
void ListenSubject(subject string)
void SendMessage(subject string, payload any)
}
class TagGenerator {
Генератор тегов
void ConnectToBroker()
void ListenSubject(subject string)
void SendMessage(subject string, payload any)
}
class Frontend {}
class Database {}
class Strapi {}
note "В дальнейшем можно написать \nдля страпи прямой проброс хуков в брокер" as N1
N1 .. Strapi
N1 .. Router
N1 .. Adapter
class Broker {
Херня для проброса данных между микросервисами
}
class Adapter {
Модуль пересылки данных в Strapi
void ConnectToBroker()
void ListenSubject(subject string)
void PublishDataToStrapi(data any)
}
Strapi --> Database : Взаимодействие с БД
Frontend <--> Router : Запросы на получение подсказок от нейронок
Frontend <--> Router : Websocket (для чата с ИИ или тому подобного)?
Frontend --> Strapi : Запросы на получение книжек и т.д.
User1 --> Nginx : Заходит на сайт
User2 --> Nginx : Заходит на сайт
Admin --> Nginx : Заходит в админку
Nginx --> Frontend : Если пользователь запрашивает ссылки без префикса
Nginx --> Router : Если префикс /api
Nginx --> Strapi : Если префикс admin
Strapi --> Router : Триггер на изменение данных (перегенерируем ИИ тэги)
Router --> Broker : Запросы к иишке
Broker --> Router : Ответы от иишки
Broker --> LinkGenerator : Запросы к генератору ссылок
LinkGenerator --> Broker : Ответы от генератора ссылок
Broker --> TagGenerator : Запуск триггера на разметку данных (можно вообще отделить эту штуку и сделать отдельным от брокера сервисом)
TagGenerator --> Broker : Данные о разметке
Broker --> Adapter : Данные о разметке
Adapter --> Strapi : Изменения в БД

note "Чисто в теории, фронт может \nтоже общаться напрямую с сервисами через gRPC" as N2
N2 .. Frontend
N2 .. Router
@enduml
