---
title: Задачи
---
%%{init: {'theme':'neutral'}}%%
flowchart TD
    subgraph Фронтенд
        A("Сверстать футер")
        B("Сверстать окно коллекции")
        E("Переверстать карточки")
        A -->|Дообсуждать реализацию карточек| E --> B
        C("Сверстать страницу просмотра текстов")
        B --> C & D
        D("Переписать markdown рендерер")
        F("Переверстать таймлайн")
        C & D --> F
        G["Подумать о странице 'О проекте'"]
        F ---> G
        K("Реализовать поиск по ключевым словам")
        C & D --> K
    end
    subgraph Бэкенд
        H("Переписать хранение статей в БД\n нужно сохранять ключевые слова")
        H <-...->|Смежная задача| C
        J["Рассмотреть возможность\nв таймлайне ссылаться на статьи"]
        J -.-> L("Добавить API для таймлайна") -.-> F
        H --> J
        L <-.-> Strapi

        subgraph Нейронка
            AI(("Разобраться с иишкой"))
            Tags[("База тэгов")]
            Texts[("База текстов")]
            Tags ==>|Выгрузка тэгов| AI
            Texts ==>|Выгрузка текстов| AI
        end
        Hook("Написать хук для Strapi\nна добавление новых текстов и тегов")
        H --> Hook <--> Strapi
        Hook --->|Триггер на генерацию тегов| AI
        Strapi[("Strapi")]
        AI ===>|Выгрузка размеченных тегов| Strapi
    end


